---
- name: Deploy WordPress on AWS EC2
  hosts: localhost
  gather_facts: false

  vars:
    # AWS credentials
    aws_access_key: *this put your aws access key account
    aws_secret_key: *this put your aws secret key account

    # EC2 instance details
    ec2_region: ap-southeast-1
    ec2_instance_type: t3.micro
    ec2_ami: *this is AMI ID
    ec2_keypair: *this is key id on instance
    ec2_security_group: *this is security group instance

    # WordPress database details
    wp_db_name: *this put db name what we define 
    wp_db_user: *this put db user what we define
    wp_db_password: *this put db password what we define

  tasks:
    - name: Create EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ ec2_region }}"
        image: "{{ ec2_ami }}"
        instance_type: "{{ ec2_instance_type }}"
        key_name: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        wait: true
        count: 1
        vpc_subnet_id: *subnet id on aws vpc
        assign_public_ip: true
      register: ec2_instance

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 120
        state: started
      with_items: "{{ ec2_instance.instances }}"

    - name: Update known hosts
      known_hosts:
        name: "{{ item.public_ip }}"
      with_items: "{{ ec2_instance.instances }}"

    - name: Configure EC2 instance
      hosts: all
      remote_user: ec2-user
      gather_facts: true
      become: true
      become_user: root
      tasks:
        - name: Install dependencies
          yum:
            name: "{{ item }}"
            state: present
          with_items:
            - httpd
            - php
            - php-mysql

        - name: Start and enable Apache service
          service:
            name: httpd
            state: started
            enabled: true

        - name: Configure firewall to allow HTTP traffic
          firewalld:
            service: http
            permanent: true
            immediate: true
            state: enabled

        - name: Download and extract WordPress
          unarchive:
            src: "https://wordpress.org/latest.tar.gz"
            dest: /var/www/html
            remote_src: true
            owner: apache
            group: apache

        - name: Configure WordPress database details
          lineinfile:
            path: "/var/www/html/wordpress/wp-config.php"
            regex: "{{ item.regex }}"
            line: "{{ item.line }}"
          with_items:
            - { regex: "database_name_here", line: "define('DB_NAME', '{{ wp_db_name }}');" }
            - { regex: "username_here", line: "define('DB_USER', '{{ wp_db_user }}');" }
            - { regex: "password_here", line: "define('DB_PASSWORD', '{{ wp_db_password }}');" }

        - name: Configure SELinux to allow HTTP connections
          selinux:
            policy: targeted
            state: permissive

        - name: Restart Apache service
          service:
            name
